on:
 push:
 schedule:
   - cron: '23 0 * * 0'
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: GitHub README Generator
        uses: th3c0d3br34ker/github-readme-info@1.0.2
        with:
          username: giuliabrambilla
          github_token: ${{ secrets.GITHUB_TOKEN }}
