on:
 push:
 schedule:
   - cron: '23 0 * * 0'
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: GitHub README Generator
        uses: th3c0d3br34ker/github-readme-info@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TIMEZONE: "Europe/Rome"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_DAILY_COMMIT: "True"
          SHOW_WEEKLY_COMMIT: "True"
          SHOW_LANGUAGE: "True"
          SHOW_TOTAL_CONTRIBUTIONS: "True"
